version: '3'
services:
  routing-lisbon:
    build:
      context: ./pub_routing-lisbon
      dockerfile: Dockerfile
    networks:
      - lisbon-net

  api-lisbon:
    build:
      context: ./pub_api-lisbon
      dockerfile: Dockerfile
    ports:
      - 8066:8000
    environment:
      - GRPC_SERVER_HOST=routing-lisbon
      - GRPC_SERVER_PORT=50051
    networks:
      - lisbon-net

networks:
  lisbon-net:
    external: false
